# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binlabeltype',
            name='organization',
            field=models.ForeignKey(help_text='The organization this label type belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bin_label_types', to='organizations.organization', verbose_name='organization'),
        ),
    ]
