# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('organizations', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this item belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicalinventorystock',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='organization',
            field=models.ForeignKey(help_text='The organization this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicalinventorystock',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The inventory item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='item',
            field=models.ForeignKey(help_text='The inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.inventoryitem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='organization',
            field=models.ForeignKey(help_text='The organization this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (null for root categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.itemcategory', verbose_name='parent category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Item category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.itemcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='bin',
            field=models.ForeignKey(help_text='The storage bin', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.storagebin', verbose_name='bin'),
        ),
        migrations.AddField(
            model_name='historicalinventorystock',
            name='bin',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The storage bin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.storagebin', verbose_name='bin'),
        ),
        migrations.AddField(
            model_name='storagebintemplate',
            name='label_type',
            field=models.ForeignKey(help_text='The label type used for bins of this template', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='inventory.binlabeltype', verbose_name='label type'),
        ),
        migrations.AddField(
            model_name='storagebintemplate',
            name='organization',
            field=models.ForeignKey(help_text='The organization this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bin_templates', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='storagebin',
            name='template',
            field=models.ForeignKey(help_text='The template defining bin configuration', on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='inventory.storagebintemplate', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='zone',
            field=models.ForeignKey(help_text='The warehouse zone this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='warehouses.warehousezone', verbose_name='zone'),
        ),
        migrations.AddField(
            model_name='storagebin',
            name='location',
            field=models.ForeignKey(help_text='The storage location this bin is at', on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.storagelocation', verbose_name='location'),
        ),
        migrations.AddConstraint(
            model_name='binlabeltype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_label_type_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='binlabeltype',
            constraint=models.UniqueConstraint(fields=('organization', 'name_en'), name='unique_label_type_name_per_org-name_en'),
        ),
        migrations.AddConstraint(
            model_name='binlabeltype',
            constraint=models.UniqueConstraint(fields=('organization', 'name_hi'), name='unique_label_type_name_per_org-name_hi'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['organization', 'parent'], name='inventory_i_organiz_9f7cae_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['code'], name='inventory_i_code_ac611a_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_category_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'sku'], name='inventory_i_organiz_e467db_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'category'], name='inventory_i_organiz_938ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_c7bf0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='unique_sku_per_org'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['bin', 'item'], name='inventory_i_bin_id_03a505_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['item', 'quantity'], name='inventory_i_item_id_f7da44_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['lot_number'], name='inventory_i_lot_num_66b480_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__97b10c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='reserved_not_exceed_quantity'),
        ),
        migrations.AddConstraint(
            model_name='storagebintemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_bin_template_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='storagebintemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name_en'), name='unique_bin_template_name_per_org-name_en'),
        ),
        migrations.AddConstraint(
            model_name='storagebintemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name_hi'), name='unique_bin_template_name_per_org-name_hi'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['zone', 'code'], name='inventory_s_zone_id_5996e9_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['aisle', 'rack', 'level'], name='inventory_s_aisle_59e728_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['location_type', 'is_active'], name='inventory_s_locatio_f4f4a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_location_code_per_zone'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['location', 'code'], name='inventory_s_locatio_eb9101_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['label_value'], name='inventory_s_label_v_3dda14_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagebin',
            constraint=models.UniqueConstraint(fields=('location', 'code'), name='unique_bin_code_per_location'),
        ),
    ]
