# Generated by Django 6.0.2 on 2026-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='is_accessible',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether drones can access this location', verbose_name='is accessible'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'is_active'], name='inventory_i_organiz_623c94_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['organization', 'sku'], name='item_org_sku_active'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['organization', 'is_active'], name='item_org_is_active_active'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['item', 'expiry_date', 'quantity'], name='inventory_i_item_id_b47a41_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['bin', 'item'], name='stock_bin_item_active'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['item', 'quantity'], name='stock_item_qty_active'),
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['location', 'is_active'], name='bin_location_is_active_active'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['zone', 'is_accessible'], name='loc_zone_access_active'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_quantity', 0), ('reorder_quantity__gte', models.F('min_stock_level')), _connector='OR'), name='reorder_quantity_gte_min_stock'),
        ),
    ]
