# Generated by Django 6.0.2 on 2026-02-19 12:47

import apps.logs.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightGraphTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_hi', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('graph_type', models.CharField(choices=[('LINE', 'Line Chart'), ('SCATTER', 'Scatter Plot'), ('BAR', 'Bar Chart'), ('AREA', 'Area Chart'), ('HISTOGRAM', 'Histogram'), ('HEATMAP', 'Heatmap'), ('BOX', 'Box Plot'), ('PATH_3D', '3D Flight Path')], default='LINE', max_length=20, verbose_name='Graph Type')),
                ('x_axis_field', models.CharField(default='timestamp', help_text='Field name for X-axis data', max_length=100, verbose_name='X-Axis Field')),
                ('y_axis_field', models.CharField(help_text='Field name for Y-axis data', max_length=100, verbose_name='Y-Axis Field')),
                ('z_axis_field', models.CharField(blank=True, default='', help_text='Field name for Z-axis data (3D graphs only)', max_length=100, verbose_name='Z-Axis Field')),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=100, verbose_name='X-Axis Label')),
                ('x_axis_label_en', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='X-Axis Label')),
                ('x_axis_label_hi', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='X-Axis Label')),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Y-Axis Label')),
                ('y_axis_label_en', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Y-Axis Label')),
                ('y_axis_label_hi', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Y-Axis Label')),
                ('z_axis_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Z-Axis Label')),
                ('z_axis_label_en', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Z-Axis Label')),
                ('z_axis_label_hi', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Z-Axis Label')),
                ('chart_config', models.JSONField(blank=True, default=dict, help_text='ECharts/visualization library configuration', verbose_name='Chart Configuration')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Flight Graph Template',
                'verbose_name_plural': 'Flight Graph Templates',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlightLogGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('title_hi', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title')),
                ('graph_data', models.JSONField(blank=True, default=dict, help_text='Processed data ready for visualization', verbose_name='Graph Data')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Is Generated')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generated At')),
                ('generation_error', models.TextField(blank=True, default='', verbose_name='Generation Error')),
                ('generation_error_en', models.TextField(blank=True, default='', null=True, verbose_name='Generation Error')),
                ('generation_error_hi', models.TextField(blank=True, default='', null=True, verbose_name='Generation Error')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_graphs/', verbose_name='Rendered Image')),
            ],
            options={
                'verbose_name': 'Flight Log Graph',
                'verbose_name_plural': 'Flight Log Graphs',
                'ordering': ['template__display_order'],
            },
        ),
        migrations.CreateModel(
            name='DroneFlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=apps.logs.models.flight_log_upload_path, verbose_name='Log File')),
                ('filename', models.CharField(help_text='Original filename', max_length=255, verbose_name='Filename')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('file_hash', models.CharField(blank=True, default='', help_text='SHA256 hash for deduplication', max_length=64, verbose_name='File Hash')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='Flight Date')),
                ('flight_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Flight Duration (seconds)')),
                ('flight_distance_meters', models.FloatField(blank=True, null=True, verbose_name='Flight Distance (meters)')),
                ('start_latitude', models.FloatField(blank=True, null=True, verbose_name='Start Latitude')),
                ('start_longitude', models.FloatField(blank=True, null=True, verbose_name='Start Longitude')),
                ('start_altitude', models.FloatField(blank=True, null=True, verbose_name='Start Altitude (m)')),
                ('end_latitude', models.FloatField(blank=True, null=True, verbose_name='End Latitude')),
                ('end_longitude', models.FloatField(blank=True, null=True, verbose_name='End Longitude')),
                ('end_altitude', models.FloatField(blank=True, null=True, verbose_name='End Altitude (m)')),
                ('max_altitude', models.FloatField(blank=True, null=True, verbose_name='Max Altitude (m)')),
                ('max_speed', models.FloatField(blank=True, null=True, verbose_name='Max Speed (m/s)')),
                ('avg_speed', models.FloatField(blank=True, null=True, verbose_name='Average Speed (m/s)')),
                ('start_battery_percent', models.FloatField(blank=True, null=True, verbose_name='Start Battery (%)')),
                ('end_battery_percent', models.FloatField(blank=True, null=True, verbose_name='End Battery (%)')),
                ('battery_used_percent', models.FloatField(blank=True, null=True, verbose_name='Battery Used (%)')),
                ('is_processed', models.BooleanField(db_index=True, default=False, verbose_name='Is Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('processing_error', models.TextField(blank=True, default='', verbose_name='Processing Error')),
                ('processing_error_en', models.TextField(blank=True, default='', null=True, verbose_name='Processing Error')),
                ('processing_error_hi', models.TextField(blank=True, default='', null=True, verbose_name='Processing Error')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Raw data extracted from log file', verbose_name='Extracted Data')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_logs', to='drones.drone', verbose_name='Drone')),
            ],
            options={
                'verbose_name': 'Drone Flight Log',
                'verbose_name_plural': 'Drone Flight Logs',
                'ordering': ['-flight_date', '-created_at'],
            },
        ),
    ]
