# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0002_initial'),
        ('organizations', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='droneflightlog',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_logs', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='droneflightlog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='flightgraphtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graph_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='flightgraphtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Leave blank for system-wide templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_templates', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='flightloggraph',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='logs.droneflightlog', verbose_name='Flight Log'),
        ),
        migrations.AddField(
            model_name='flightloggraph',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_graphs', to='logs.flightgraphtemplate', verbose_name='Template'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['organization', 'is_processed'], name='logs_dronef_organiz_64f026_idx'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['drone', 'flight_date'], name='logs_dronef_drone_i_2d99a7_idx'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['file_hash'], name='logs_dronef_file_ha_d8aa17_idx'),
        ),
        migrations.AddConstraint(
            model_name='flightgraphtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_graph_template_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='flightgraphtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name_en'), name='unique_graph_template_name_per_org-name_en'),
        ),
        migrations.AddConstraint(
            model_name='flightgraphtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name_hi'), name='unique_graph_template_name_per_org-name_hi'),
        ),
        migrations.AddConstraint(
            model_name='flightloggraph',
            constraint=models.UniqueConstraint(fields=('log', 'template'), name='unique_graph_per_log_template'),
        ),
    ]
