# Generated by Django 6.0.2 on 2026-02-20 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_drone_drone_work_area_status_active_and_more'),
        ('logs', '0003_initial'),
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['flight_date'], name='logs_dronef_flight__047f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['-flight_date'], name='logs_dronef_flight__3762bc_idx'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['drone', '-flight_date'], name='logs_dronef_drone_i_90c268_idx'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['organization', 'flight_date'], name='logs_dronef_organiz_d1da8c_idx'),
        ),
        migrations.AddIndex(
            model_name='droneflightlog',
            index=models.Index(fields=['organization', 'drone', 'flight_date'], name='logs_dronef_organiz_6bbfd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='droneflightlog',
            constraint=models.CheckConstraint(condition=models.Q(('start_battery_percent__isnull', True), ('end_battery_percent__isnull', True), ('end_battery_percent__lte', models.F('start_battery_percent')), _connector='OR'), name='battery_decreases_during_flight'),
        ),
        migrations.AddConstraint(
            model_name='droneflightlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_processed', False), ('processed_at__isnull', True)), ('is_processed', True), _connector='OR'), name='processed_at_requires_is_processed'),
        ),
    ]
