# Generated by Django 6.0.2 on 2026-03-06 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_historicalsubscription_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('ORDER_STATUS_CHANGED', 'Order Status Changed'), ('ORDER_OVERDUE', 'Order Overdue'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_FAILED', 'Job Failed'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('IMPORT_COMPLETED', 'Import Completed'), ('IMPORT_FAILED', 'Import Failed'), ('DRONE_MAINTENANCE_DUE', 'Drone Maintenance Due'), ('BATTERY_LOW_HEALTH', 'Battery Low Health'), ('NEW_MEMBER_JOINED', 'New Member Joined'), ('SYSTEM', 'System Notification')], db_index=True, max_length=30, verbose_name='Notification Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('link', models.CharField(blank=True, default='', help_text='Frontend route to navigate to (e.g., /dashboard/orders)', max_length=500, verbose_name='Link')),
                ('source_type', models.CharField(blank=True, default='', help_text='Model name that triggered this notification', max_length=50, verbose_name='Source Type')),
                ('source_id', models.CharField(blank=True, default='', help_text='UUID of the source object', max_length=100, verbose_name='Source ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(help_text='The user this notification is for', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'user', '-created_at'], name='notificatio_organiz_54966b_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
