# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number with country code (e.g., +91 9876543210)', max_length=128, null=True, region='IN', verbose_name='Phone Number')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('VIEWER', 'Viewer')], db_index=True, default='VIEWER', max_length=20, verbose_name='Role')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Email Verified')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/', verbose_name='Profile Picture')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('lockout_until', models.DateTimeField(blank=True, help_text='Account is locked until this time due to failed login attempts', null=True, verbose_name='Locked Until')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this account', verbose_name='Two-Factor Enabled')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Last time the password was changed', null=True, verbose_name='Password Changed At')),
                ('force_password_change', models.BooleanField(default=False, help_text='Require password change on next login', verbose_name='Force Password Change')),
                ('active_organization', models.ForeignKey(blank=True, help_text='Currently active organization for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='organizations.organization', verbose_name='Active Organization')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_email', models.EmailField(max_length=254, verbose_name='Old Email')),
                ('new_email', models.EmailField(max_length=254, verbose_name='New Email')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Change Request',
                'verbose_name_plural': 'Email Change Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('failure_reason', models.CharField(blank=True, max_length=100, verbose_name='Failure Reason')),
                ('two_factor_used', models.BooleanField(default=False, verbose_name='Two-Factor Used')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='users_login_email_9feded_idx'), models.Index(fields=['ip_address', 'created_at'], name='users_login_ip_addr_4650d9_idx'), models.Index(fields=['success', 'created_at'], name='users_login_success_da8986_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('otp', models.CharField(max_length=6, verbose_name='OTP')),
                ('otp_type', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('PHONE_VERIFICATION', 'Phone Verification'), ('EMAIL_CHANGE', 'Email Change Verification')], default='EMAIL_VERIFICATION', max_length=20, verbose_name='OTP Type')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Maximum Attempts')),
                ('new_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='New Email')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'otp_type', 'is_used'], name='users_otp_email_758e66_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.CharField(max_length=255, verbose_name='Password Hash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(help_text='TOTP secret key (base32 encoded)', max_length=32, verbose_name='Secret Key')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('backup_codes', models.JSONField(default=list, help_text='Hashed backup recovery codes', verbose_name='Backup Codes')),
                ('backup_codes_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Backup Codes Generated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, help_text='Detected device type (mobile, tablet, desktop)', max_length=50, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('location', models.CharField(blank=True, help_text='Approximate location based on IP', max_length=200, verbose_name='Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_user_email_3f6199_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', 'created_at'], name='users_passw_user_id_053982_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_3887fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='users_users_session_70af4d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='users_users_expires_76a1e6_idx'),
        ),
    ]
