# Generated by Django 6.0.2 on 2026-02-20 11:42

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='location',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Approximate location based on IP', max_length=200, verbose_name='Location')),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['created_at'], name='users_login_created_130efb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified', 'is_active'], name='users_user_is_veri_6fe005_idx'),
        ),
        migrations.AddConstraint(
            model_name='twofactorauth',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_2fa_per_user'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gte', models.F('created_at'))), name='session_expires_after_created'),
        ),
    ]
