# Generated by Django 6.0.2 on 2026-03-05 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersession_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_UPDATE', 'Profile Update')], db_index=True, max_length=20, verbose_name='Action')),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='Type of resource affected (e.g., Drone, Order, Item)', max_length=50, verbose_name='Resource Type')),
                ('resource_id', models.CharField(blank=True, help_text='ID or UUID of the affected resource', max_length=100, verbose_name='Resource ID')),
                ('resource_name', models.CharField(blank=True, help_text='Display name of the affected resource', max_length=200, verbose_name='Resource Name')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the activity', verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_usera_user_id_63b4df_idx'), models.Index(fields=['action', 'created_at'], name='users_usera_action_6770a8_idx'), models.Index(fields=['resource_type', 'created_at'], name='users_usera_resourc_88574b_idx'), models.Index(fields=['created_at'], name='users_usera_created_828ca1_idx')],
            },
        ),
    ]
