# Generated by Django 6.0.2 on 2026-03-05 13:03

import apps.core.choices
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], help_text='Color theme preference', max_length=10, null=True, verbose_name='Theme')),
                ('timezone', models.CharField(blank=True, help_text='Personal timezone override', max_length=64, null=True, validators=[apps.core.choices.validate_timezone], verbose_name='Timezone')),
                ('date_format', models.CharField(blank=True, choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], help_text='Personal date format preference', max_length=20, null=True, verbose_name='Date Format')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi')], help_text='Personal language preference', max_length=10, null=True, verbose_name='Language')),
                ('email_notifications_enabled', models.BooleanField(blank=True, help_text='Personal email notification preference', null=True, verbose_name='Email Notifications Enabled')),
                ('daily_summary_enabled', models.BooleanField(blank=True, help_text='Personal daily summary preference', null=True, verbose_name='Daily Summary Enabled')),
                ('daily_summary_time', models.TimeField(blank=True, help_text='Personal daily summary time', null=True, verbose_name='Daily Summary Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
