# Generated by Django 6.0.2 on 2026-03-05 13:03

from django.db import migrations


def create_preferences_for_existing_users(apps, schema_editor):
    """Create UserPreferences for all existing users that don't have one."""
    User = apps.get_model("users", "User")
    UserPreferences = apps.get_model("users", "UserPreferences")

    users_without_preferences = User.objects.exclude(
        preferences__isnull=False
    )
    preferences = [
        UserPreferences(user=user) for user in users_without_preferences
    ]
    UserPreferences.objects.bulk_create(preferences, ignore_conflicts=True)


def reverse_migration(apps, schema_editor):
    """Remove all UserPreferences (reverse migration)."""
    UserPreferences = apps.get_model("users", "UserPreferences")
    UserPreferences.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userpreferences"),
    ]

    operations = [
        migrations.RunPython(
            create_preferences_for_existing_users,
            reverse_migration,
        ),
    ]
