# Generated by Django 6.0.2 on 2026-02-19 12:47

import apps.core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('import_type', models.CharField(choices=[('ITEMS', 'Inventory Items'), ('LOCATIONS', 'Storage Locations'), ('INVENTORY', 'Inventory Stock'), ('ORDERS', 'Orders'), ('CATEGORIES', 'Item Categories')], max_length=20, verbose_name='Import Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=25, verbose_name='Status')),
                ('file', models.FileField(help_text='CSV or Excel file to import', upload_to=apps.core.utils.import_file_upload_path, verbose_name='Import File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total Rows')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Processed Rows')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Success Count')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Error Count')),
                ('skipped_count', models.PositiveIntegerField(default=0, help_text='Rows skipped (duplicates, unchanged)', verbose_name='Skipped Count')),
                ('error_file', models.FileField(blank=True, help_text='CSV file with failed rows and error details', null=True, upload_to=apps.core.utils.import_error_file_upload_path, verbose_name='Error Report')),
                ('error_summary', models.JSONField(blank=True, default=list, help_text='Summary of errors [{row, field, error}]', verbose_name='Error Summary')),
                ('error_message', models.TextField(blank=True, default='', help_text='General error message if import failed', verbose_name='Error Message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
