# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Required for location and inventory imports', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['organization', 'status'], name='core_import_organiz_fc31c0_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['import_type', 'status'], name='core_import_import__f3a965_idx'),
        ),
    ]
