# Generated by Django 6.0.2 on 2026-02-20 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('total_rows', 0), ('processed_rows__lte', models.F('total_rows')), _connector='OR'), name='processed_not_exceed_total_rows'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('error_count__lte', models.F('processed_rows')), ('skipped_count__lte', models.F('processed_rows')), ('success_count__lte', models.F('processed_rows'))), name='counts_not_exceed_processed'),
        ),
    ]
