# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0001_initial'),
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryswaprecord',
            name='drone',
            field=models.ForeignKey(help_text='The drone that had its battery swapped', on_delete=django.db.models.deletion.PROTECT, related_name='battery_swaps', to='drones.drone', verbose_name='drone'),
        ),
    ]
