# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0002_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryswaprecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the swap', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_swaps_performed', to=settings.AUTH_USER_MODEL, verbose_name='performed by'),
        ),
        migrations.AddField(
            model_name='dronebattery',
            name='warehouse',
            field=models.ForeignKey(help_text='The warehouse this battery belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='warehouses.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='batteryswaprecord',
            name='new_battery',
            field=models.ForeignKey(help_text='The battery installed on the drone', on_delete=django.db.models.deletion.PROTECT, related_name='swaps_installed', to='batteries.dronebattery', verbose_name='new battery'),
        ),
        migrations.AddField(
            model_name='batteryswaprecord',
            name='old_battery',
            field=models.ForeignKey(blank=True, help_text='The battery removed from the drone (null if first installation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='swaps_removed', to='batteries.dronebattery', verbose_name='old battery'),
        ),
        migrations.AddField(
            model_name='batterychargingsession',
            name='battery',
            field=models.ForeignKey(help_text='The battery that was charged', on_delete=django.db.models.deletion.PROTECT, related_name='charging_sessions', to='batteries.dronebattery', verbose_name='battery'),
        ),
        migrations.AddField(
            model_name='historicaldronebattery',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldronebattery',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The warehouse this battery belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouses.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddIndex(
            model_name='dronebattery',
            index=models.Index(fields=['status', 'health_status'], name='batteries_d_status_3a9f73_idx'),
        ),
        migrations.AddIndex(
            model_name='dronebattery',
            index=models.Index(fields=['warehouse', 'status'], name='batteries_d_warehou_6da788_idx'),
        ),
        migrations.AddIndex(
            model_name='dronebattery',
            index=models.Index(fields=['cycle_count'], name='batteries_d_cycle_c_e59eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='dronebattery',
            constraint=models.CheckConstraint(condition=models.Q(('current_charge_percent__lte', 100)), name='battery_charge_max_100'),
        ),
        migrations.AddConstraint(
            model_name='dronebattery',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_count__lte', django.db.models.expressions.CombinedExpression(models.F('max_cycles'), '+', models.Value(100)))), name='battery_cycles_reasonable'),
        ),
        migrations.AddIndex(
            model_name='batteryswaprecord',
            index=models.Index(fields=['drone', '-swapped_at'], name='batteries_b_drone_i_caac3a_idx'),
        ),
        migrations.AddIndex(
            model_name='batteryswaprecord',
            index=models.Index(fields=['old_battery', '-swapped_at'], name='batteries_b_old_bat_fafe44_idx'),
        ),
        migrations.AddIndex(
            model_name='batteryswaprecord',
            index=models.Index(fields=['new_battery', '-swapped_at'], name='batteries_b_new_bat_3369fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='batteryswaprecord',
            constraint=models.CheckConstraint(condition=models.Q(('old_battery', models.F('new_battery')), _negated=True), name='different_batteries_swap'),
        ),
        migrations.AddIndex(
            model_name='batterychargingsession',
            index=models.Index(fields=['battery', '-started_at'], name='batteries_b_battery_1c5fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='batterychargingsession',
            index=models.Index(fields=['status', '-started_at'], name='batteries_b_status_e3cd70_idx'),
        ),
    ]
