# Generated by Django 6.0.2 on 2026-02-20 11:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_initial'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batterychargingsession',
            index=models.Index(fields=['started_at'], name='batteries_b_started_50717e_idx'),
        ),
        migrations.AddIndex(
            model_name='batterychargingsession',
            index=models.Index(fields=['-started_at'], name='batteries_b_started_203e42_idx'),
        ),
        migrations.AddIndex(
            model_name='batterychargingsession',
            index=models.Index(fields=['battery', 'status', '-started_at'], name='batteries_b_battery_4f4c53_idx'),
        ),
        migrations.AddIndex(
            model_name='dronebattery',
            index=models.Index(fields=['warehouse', 'status', 'health_status', 'current_charge_percent'], name='batteries_d_warehou_74933d_idx'),
        ),
        migrations.AddIndex(
            model_name='dronebattery',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['warehouse', 'status'], name='battery_wh_status_active'),
        ),
        migrations.AddIndex(
            model_name='dronebattery',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['status', 'health_status'], name='battery_status_health_active'),
        ),
        migrations.AddConstraint(
            model_name='batterychargingsession',
            constraint=models.CheckConstraint(condition=models.Q(('end_charge_percent__isnull', True), ('end_charge_percent__gte', models.F('start_charge_percent')), _connector='OR'), name='charging_increases_charge'),
        ),
        migrations.AddConstraint(
            model_name='dronebattery',
            constraint=models.CheckConstraint(condition=models.Q(('current_capacity_mah__isnull', True), ('current_capacity_mah__lte', models.F('capacity_mah')), _connector='OR'), name='current_capacity_not_exceed_nominal'),
        ),
        migrations.AddConstraint(
            model_name='dronebattery',
            constraint=models.CheckConstraint(condition=models.Q(('voltage_nominal__gte', django.db.models.expressions.CombinedExpression(models.F('cell_count'), '*', models.Value(3.0))), ('voltage_nominal__lte', django.db.models.expressions.CombinedExpression(models.F('cell_count'), '*', models.Value(4.2)))), name='voltage_matches_cell_count'),
        ),
    ]
