# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0003_initial'),
        ('drones', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='work_area',
            field=models.ForeignKey(help_text='Work area where this drone operates', on_delete=django.db.models.deletion.PROTECT, related_name='drones', to='warehouses.droneworkarea', verbose_name='Work Area'),
        ),
        migrations.AddField(
            model_name='dronemaintenancerecord',
            name='drone',
            field=models.ForeignKey(help_text='Drone that was maintained', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='drones.drone', verbose_name='Drone'),
        ),
        migrations.AddField(
            model_name='dronemaintenancerecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the maintenance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
        migrations.AddField(
            model_name='dronetelemetrylog',
            name='drone',
            field=models.ForeignKey(help_text='Drone that generated this telemetry', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='drones.drone', verbose_name='Drone'),
        ),
        migrations.AddField(
            model_name='historicaldrone',
            name='current_battery',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Battery currently attached to this drone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='batteries.dronebattery', verbose_name='Current Battery'),
        ),
        migrations.AddField(
            model_name='historicaldrone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldrone',
            name='work_area',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Work area where this drone operates', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouses.droneworkarea', verbose_name='Work Area'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['work_area', 'is_active'], name='drones_dron_work_ar_304548_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['status'], name='drones_dron_status_9ef48e_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['serial_number'], name='drones_dron_serial__75848e_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['last_heartbeat'], name='drones_dron_last_he_ff7e48_idx'),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancerecord',
            index=models.Index(fields=['drone', 'created_at'], name='drones_dron_drone_i_10ede7_idx'),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancerecord',
            index=models.Index(fields=['maintenance_type'], name='drones_dron_mainten_3518f9_idx'),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancerecord',
            index=models.Index(fields=['completed_at'], name='drones_dron_complet_6e6ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['drone', 'timestamp'], name='drones_dron_drone_i_9abd04_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['timestamp'], name='drones_dron_timesta_09672c_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['flight_mode'], name='drones_dron_flight__32a030_idx'),
        ),
    ]
