# Generated by Django 6.0.2 on 2026-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_batterychargingsession_batteries_b_started_50717e_idx_and_more'),
        ('drones', '0002_initial'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['work_area', 'status'], name='drone_work_area_status_active'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['status', 'is_active'], name='drone_status_is_active_active'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['drone', '-timestamp'], name='drones_dron_drone_i_7f6d48_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['drone'], name='drones_dron_drone_i_828c90_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['-timestamp'], name='drones_dron_timesta_9d68ed_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['drone', 'flight_mode', 'timestamp'], name='drones_dron_drone_i_cdba1f_idx'),
        ),
        migrations.AddIndex(
            model_name='dronetelemetrylog',
            index=models.Index(fields=['drone', 'battery_percentage', 'timestamp'], name='drones_dron_drone_i_cee3f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='drone',
            constraint=models.CheckConstraint(condition=models.Q(('total_flight_hours__gte', 0)), name='non_negative_flight_hours'),
        ),
        migrations.AddConstraint(
            model_name='drone',
            constraint=models.CheckConstraint(condition=models.Q(('total_distance_km__gte', 0)), name='non_negative_flight_distance'),
        ),
    ]
