# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Order Number')),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', help_text='Reference from external system (ERP, WMS, etc.)', max_length=100, verbose_name='External Reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20, verbose_name='Priority')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Customer Name')),
                ('customer_code', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Customer Code')),
                ('shipping_address_line1', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1')),
                ('shipping_address_line2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2')),
                ('shipping_city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('shipping_state', models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
                ('shipping_postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('shipping_country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('picking_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Picking Started At')),
                ('picking_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Picking Completed At')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='Packed At')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation Reason')),
                ('cancellation_reason_en', models.TextField(blank=True, default='', null=True, verbose_name='Cancellation Reason')),
                ('cancellation_reason_hi', models.TextField(blank=True, default='', null=True, verbose_name='Cancellation Reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('internal_notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Internal Notes')),
                ('internal_notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Pick Order',
                'verbose_name_plural': 'Pick Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickOrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Batch Number')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Batch Name')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Batch Name')),
                ('name_hi', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Batch Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Pick Order Batch',
                'verbose_name_plural': 'Pick Order Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to pick', verbose_name='Quantity')),
                ('picked_quantity', models.PositiveIntegerField(default=0, help_text='Quantity actually picked', verbose_name='Picked Quantity')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='Line Number')),
                ('is_picked', models.BooleanField(db_index=True, default=False, verbose_name='Is Picked')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='Picked At')),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Lot Number')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('pick_notes', models.TextField(blank=True, default='', help_text='Notes recorded during picking', verbose_name='Pick Notes')),
                ('pick_notes_en', models.TextField(blank=True, default='', help_text='Notes recorded during picking', null=True, verbose_name='Pick Notes')),
                ('pick_notes_hi', models.TextField(blank=True, default='', help_text='Notes recorded during picking', null=True, verbose_name='Pick Notes')),
            ],
            options={
                'verbose_name': 'Pick Order Line',
                'verbose_name_plural': 'Pick Order Lines',
                'ordering': ['order', 'line_number'],
            },
        ),
    ]
