# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='pickorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pickorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='pickorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='pickorderbatch',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='pickorderbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pickorderbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_batches', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='pickorderbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_batches', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='pickorder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.pickorderbatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='pickorderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.inventoryitem', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='pickorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.pickorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='pickorderline',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_lines', to=settings.AUTH_USER_MODEL, verbose_name='Picked By'),
        ),
        migrations.AddField(
            model_name='pickorderline',
            name='source_bin',
            field=models.ForeignKey(help_text='Bin from which item should be picked', on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.storagebin', verbose_name='Source Bin'),
        ),
        migrations.AddField(
            model_name='pickorderline',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Specific stock record to pick from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='inventory.inventorystock', verbose_name='Stock Record'),
        ),
        migrations.AddIndex(
            model_name='pickorderbatch',
            index=models.Index(fields=['organization', 'is_completed'], name='orders_pick_organiz_21705b_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorderbatch',
            index=models.Index(fields=['warehouse', 'is_completed'], name='orders_pick_warehou_501588_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['organization', 'status'], name='orders_pick_organiz_282f02_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['warehouse', 'status'], name='orders_pick_warehou_81b334_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['order_date'], name='orders_pick_order_d_23a462_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['due_date'], name='orders_pick_due_dat_a09433_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['priority', 'status'], name='orders_pick_priorit_46af65_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorderline',
            index=models.Index(fields=['order', 'is_picked'], name='orders_pick_order_i_40ceee_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorderline',
            index=models.Index(fields=['item'], name='orders_pick_item_id_9c4734_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorderline',
            index=models.Index(fields=['source_bin'], name='orders_pick_source__4ce90d_idx'),
        ),
    ]
