# Generated by Django 6.0.2 on 2026-02-20 11:42

import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_storagelocation_is_accessible_and_more'),
        ('orders', '0002_initial'),
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPickOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, verbose_name='Order Number')),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', help_text='Reference from external system (ERP, WMS, etc.)', max_length=100, verbose_name='External Reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('PACKING', 'Packing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20, verbose_name='Priority')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Customer Name')),
                ('customer_code', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Customer Code')),
                ('shipping_address_line1', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1'))),
                ('shipping_address_line2', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2'))),
                ('shipping_city', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100, verbose_name='City'))),
                ('shipping_state', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100, verbose_name='State'))),
                ('shipping_postal_code', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code'))),
                ('shipping_country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('picking_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Picking Started At')),
                ('picking_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Picking Completed At')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='Packed At')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the order was assigned to a picker', null=True, verbose_name='Assigned At')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation Reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Pick Order',
                'verbose_name_plural': 'historical Pick Orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='pickorder',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the order was assigned to a picker', null=True, verbose_name='Assigned At'),
        ),
        migrations.AlterField(
            model_name='pickorder',
            name='shipping_address_line1',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1')),
        ),
        migrations.AlterField(
            model_name='pickorder',
            name='shipping_address_line2',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2')),
        ),
        migrations.AlterField(
            model_name='pickorder',
            name='shipping_city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
        ),
        migrations.AlterField(
            model_name='pickorder',
            name='shipping_postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
        ),
        migrations.AlterField(
            model_name='pickorder',
            name='shipping_state',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['organization', 'status', 'priority'], name='orders_pick_organiz_395f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['warehouse', 'status', 'due_date'], name='orders_pick_warehou_523361_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['assigned_to', 'status'], name='orders_pick_assigne_e547a2_idx'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['organization', 'status'], name='order_org_status_active'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['warehouse', 'status', 'priority'], name='order_wh_stat_pri_active'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['due_date'], name='order_due_date_active'),
        ),
        migrations.AddIndex(
            model_name='pickorderbatch',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['organization', 'is_completed'], name='batch_org_completed_active'),
        ),
        migrations.AddConstraint(
            model_name='pickorder',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('order_date')), _connector='OR'), name='due_date_after_order_date'),
        ),
        migrations.AddConstraint(
            model_name='pickorderline',
            constraint=models.CheckConstraint(condition=models.Q(('picked_quantity__lte', models.F('quantity'))), name='order_line_picked_not_exceed_quantity'),
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.pickorderbatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
    ]
