# Generated by Django 5.1.7 on 2026-03-11 06:15

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_historicalpickorder_pickorder_assigned_at_and_more'),
        ('organizations', '0004_alter_historicalsubscription_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Customer Code')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', verbose_name='Phone')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Person')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('gst_number', models.CharField(blank=True, default='', max_length=15, verbose_name='GST Number')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalpickorder',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Link to customer record. Auto-fills name and code.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='pickorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Link to customer record. Auto-fills name and code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer', verbose_name='Customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'is_active'], name='orders_cust_organiz_4f1aef_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['organization', 'name'], name='customer_org_name_active'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'code')},
        ),
    ]
