# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('NAVIGATING', 'Navigating'), ('ARRIVED', 'Arrived'), ('SCANNED', 'Scanned'), ('PICKED', 'Picked'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('ERROR', 'Error')], db_index=True, max_length=20, verbose_name='Event Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('x_position', models.FloatField(blank=True, null=True, verbose_name='X Position')),
                ('y_position', models.FloatField(blank=True, null=True, verbose_name='Y Position')),
                ('z_position', models.FloatField(blank=True, null=True, verbose_name='Z Position')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Drone Job Event',
                'verbose_name_plural': 'Drone Job Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('job_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Job Number')),
                ('job_type', models.CharField(choices=[('PICK', 'Pick'), ('SCAN', 'Scan'), ('COUNT', 'Count'), ('MOVE', 'Move'), ('RETURN_HOME', 'Return Home')], default='PICK', max_length=20, verbose_name='Job Type')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], db_index=True, default='NEW', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20, verbose_name='Priority')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('picked_quantity', models.PositiveIntegerField(default=0, verbose_name='Picked Quantity')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Queued At')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Failed At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('error_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('error_message_en', models.TextField(blank=True, default='', null=True, verbose_name='Error Message')),
                ('error_message_hi', models.TextField(blank=True, default='', null=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('internal_notes_en', models.TextField(blank=True, default='', null=True, verbose_name='Internal Notes')),
                ('internal_notes_hi', models.TextField(blank=True, default='', null=True, verbose_name='Internal Notes')),
                ('destination_bin', models.ForeignKey(blank=True, help_text='Bin to deliver to (for move jobs)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_jobs', to='inventory.storagebin', verbose_name='Destination Bin')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='drones.drone', verbose_name='Assigned Drone')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='inventory.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Drone Job',
                'verbose_name_plural': 'Drone Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
