# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('jobs', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronejob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='dronejob',
            name='source_bin',
            field=models.ForeignKey(blank=True, help_text='Bin to pick from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_jobs', to='inventory.storagebin', verbose_name='Source Bin'),
        ),
    ]
