# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0002_initial'),
        ('jobs', '0003_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronejob',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='warehouses.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='dronejobevent',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to='drones.drone', verbose_name='Drone'),
        ),
        migrations.AddField(
            model_name='dronejobevent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.dronejob', verbose_name='Job'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['organization', 'status'], name='jobs_dronej_organiz_7aef26_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['warehouse', 'status'], name='jobs_dronej_warehou_649d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['drone', 'status'], name='jobs_dronej_drone_i_8719e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['priority', 'status'], name='jobs_dronej_priorit_31e94c_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['order'], name='jobs_dronej_order_i_b97163_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejobevent',
            index=models.Index(fields=['job', 'event_type'], name='jobs_dronej_job_id_077bef_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejobevent',
            index=models.Index(fields=['created_at'], name='jobs_dronej_created_1a7b07_idx'),
        ),
    ]
