# Generated by Django 6.0.2 on 2026-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_drone_drone_work_area_status_active_and_more'),
        ('inventory', '0004_alter_storagelocation_is_accessible_and_more'),
        ('jobs', '0004_initial'),
        ('orders', '0003_historicalpickorder_pickorder_assigned_at_and_more'),
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronejobevent',
            name='x_position',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='X Position'),
        ),
        migrations.AlterField(
            model_name='dronejobevent',
            name='y_position',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Y Position'),
        ),
        migrations.AlterField(
            model_name='dronejobevent',
            name='z_position',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Z Position'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['created_at'], name='jobs_dronej_created_8b186e_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['-created_at'], name='jobs_dronej_created_c435de_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['completed_at'], name='jobs_dronej_complet_216577_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['-completed_at'], name='jobs_dronej_complet_01a22a_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='jobs_dronej_organiz_4e22b2_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['warehouse', 'status', '-created_at'], name='jobs_dronej_warehou_22e5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(fields=['drone', '-completed_at'], name='jobs_dronej_drone_i_296e83_idx'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['organization', 'status'], name='job_org_status_active'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['warehouse', 'status', 'priority'], name='job_wh_status_priority_active'),
        ),
        migrations.AddIndex(
            model_name='dronejob',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['drone', 'status'], name='job_drone_status_active'),
        ),
        migrations.AddConstraint(
            model_name='dronejob',
            constraint=models.CheckConstraint(condition=models.Q(('picked_quantity__lte', models.F('quantity'))), name='job_picked_not_exceed_quantity'),
        ),
    ]
