# Generated by Django 6.0.2 on 2026-02-20 11:42

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwarehousezone',
            name='is_no_fly_zone',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, drones cannot enter this zone', verbose_name='Is No-Fly Zone'),
        ),
        migrations.AlterField(
            model_name='warehousecontact',
            name='phone_primary',
            field=django_cryptography.fields.encrypt(models.CharField(help_text='Primary contact number', max_length=20, verbose_name='Primary Phone')),
        ),
        migrations.AlterField(
            model_name='warehousecontact',
            name='phone_secondary',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Secondary contact number', max_length=20, verbose_name='Secondary Phone')),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='emergency_contact_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, verbose_name='Emergency Contact')),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='operates_24x7',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the warehouse operates round the clock', verbose_name='Operates 24x7'),
        ),
        migrations.AlterField(
            model_name='warehousezone',
            name='is_no_fly_zone',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, drones cannot enter this zone', verbose_name='Is No-Fly Zone'),
        ),
        migrations.AddConstraint(
            model_name='droneworkarea',
            constraint=models.CheckConstraint(condition=models.Q(('min_x__isnull', True), ('max_x__isnull', True), ('min_x__lt', models.F('max_x')), _connector='OR'), name='work_area_min_x_less_than_max_x'),
        ),
        migrations.AddConstraint(
            model_name='droneworkarea',
            constraint=models.CheckConstraint(condition=models.Q(('min_y__isnull', True), ('max_y__isnull', True), ('min_y__lt', models.F('max_y')), _connector='OR'), name='work_area_min_y_less_than_max_y'),
        ),
        migrations.AddConstraint(
            model_name='droneworkarea',
            constraint=models.CheckConstraint(condition=models.Q(('min_z__lt', models.F('max_z'))), name='work_area_min_z_less_than_max_z'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('operates_24x7', True), ('operating_hours_start__isnull', True), ('operating_hours_end__isnull', True), ('operating_hours_start__lt', models.F('operating_hours_end')), _connector='OR'), name='valid_operating_hours'),
        ),
        migrations.AddConstraint(
            model_name='warehousezone',
            constraint=models.CheckConstraint(condition=models.Q(('min_x__isnull', True), ('max_x__isnull', True), ('min_x__lt', models.F('max_x')), _connector='OR'), name='zone_min_x_less_than_max_x'),
        ),
        migrations.AddConstraint(
            model_name='warehousezone',
            constraint=models.CheckConstraint(condition=models.Q(('min_y__isnull', True), ('max_y__isnull', True), ('min_y__lt', models.F('max_y')), _connector='OR'), name='zone_min_y_less_than_max_y'),
        ),
    ]
