# Generated by Django 6.0.2 on 2026-03-05 12:23

import apps.core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_historicalwarehousezone_is_no_fly_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='Warehouse timezone for scheduling', max_length=64, validators=[apps.core.choices.validate_timezone], verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='Warehouse timezone for scheduling', max_length=64, validators=[apps.core.choices.validate_timezone], verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='currency',
            field=models.CharField(default='INR', help_text='Default currency for warehouse operations', max_length=3, validators=[apps.core.choices.validate_currency], verbose_name='Currency'),
        ),
    ]
