# Generated by Django 6.0.2 on 2026-02-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organization owner/creator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='historicalorganizationapikey',
            name='created_by_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this API key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicalorganizationapikey',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorganizationinvitation',
            name='accepted_by_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who accepted the invitation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AddField(
            model_name='historicalorganizationinvitation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorganizationinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AddField(
            model_name='historicalorganizationmembership',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorganizationmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AddField(
            model_name='historicalorganizationmembership',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user who is a member', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(help_text='Organization owner/creator', on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this subscription belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='historicalorganizationmembership',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this membership belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='historicalorganizationinvitation',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization being invited to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='historicalorganizationapikey',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this API key belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='created_by_user',
            field=models.ForeignKey(help_text='User who created this API key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='organization',
            field=models.ForeignKey(help_text='The organization this API key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='accepted_by_user',
            field=models.ForeignKey(blank=True, help_text='User who accepted the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='invited_by',
            field=models.ForeignKey(help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='organization',
            field=models.ForeignKey(help_text='The organization being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_membership_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(help_text='The organization this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Current subscription plan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The subscribed plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Current subscription plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(help_text='The organization this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text='The subscribed plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organizations.plan', verbose_name='Plan'),
        ),
        migrations.AddIndex(
            model_name='organizationapikey',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_2876d0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationapikey',
            index=models.Index(fields=['prefix'], name='organizatio_prefix_e85404_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_68c8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['email', 'status'], name='organizatio_email_2c8ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitation',
            index=models.Index(fields=['expires_at'], name='organizatio_expires_dc048c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_c1d93c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_494b92_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['membership_role'], name='organizatio_members_058620_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_048085_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'is_verified'], name='organizatio_is_acti_0f3bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner'], name='organizatio_owner_i_370edd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='organizatio_status_e8c375_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='organizatio_current_c42776_idx'),
        ),
    ]
