# Generated by Django 6.0.2 on 2026-02-20 11:42

import django.core.validators
import django.db.models.expressions
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizationapikey',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=60, help_text='API requests allowed per minute', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rate Limit'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='payment_method',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Last used payment method (e.g., card_xxxx)', max_length=50, verbose_name='Payment Method')),
        ),
        migrations.AlterField(
            model_name='organizationapikey',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=60, help_text='API requests allowed per minute', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rate Limit'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='password_expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Days before password expires (0 = never)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Password Expiry Days'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='webhook_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Secret for webhook signature verification', max_length=64, verbose_name='Webhook Secret')),
        ),
        migrations.AlterField(
            model_name='plan',
            name='api_rate_limit_per_minute',
            field=models.PositiveIntegerField(default=60, help_text='API requests allowed per minute', validators=[django.core.validators.MinValueValidator(1)], verbose_name='API Rate Limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this plan is available for new subscriptions', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Last used payment method (e.g., card_xxxx)', max_length=50, verbose_name='Payment Method')),
        ),
        migrations.AddConstraint(
            model_name='organizationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('battery_critical_threshold_percent__lt', models.F('battery_low_threshold_percent'))), name='critical_less_than_low_threshold'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('annual_price__lte', django.db.models.expressions.CombinedExpression(models.F('monthly_price'), '*', models.Value(12)))), name='annual_price_not_exceed_monthly'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_start__lt', models.F('current_period_end'))), name='subscription_period_end_after_start'),
        ),
    ]
