# Generated by Django 6.0.2 on 2026-03-05 12:23

import apps.core.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_historicalorganizationapikey_rate_limit_per_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscription',
            name='currency',
            field=models.CharField(default='INR', max_length=3, validators=[apps.core.choices.validate_currency], verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='currency',
            field=models.CharField(default='INR', max_length=3, validators=[apps.core.choices.validate_currency], verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64, validators=[apps.core.choices.validate_timezone], verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='INR', max_length=3, validators=[apps.core.choices.validate_currency], verbose_name='Currency'),
        ),
    ]
